### ISSUE TITLE
Total precache size is about 0 B for 0 resources Ask Question

### ISSUE THREAD

**Issue by simran66** [sparanoid/grunt-service-worker#2]
With grunt-sw-precache, I am trying to cache my application:

```
'develop': {
        navigateFallback: 'index.html',
        staticFileGlobs: [ '**/*.{js}'],
        stripPrefix: 'app',
        baseDir:'app',
        runtimeCaching: [{
          handler: 'networkFirst'
        }]
      },
    },
```

I tried different patterns. Always the same result

 `My directory structure looks like this:  projectRoot       
         ______app          
               __________images         
               __________styles         
               __________controllers              
              __________jsFilesHere              
              ___________app.js              
              _____________config.js             
              _____________index.html            
             _____________sw.js 

I need to cache all my files to enable the application to run offline as well. For that matter I need to cache my entire app folderHow do I change thisstaticFileGlobs: ['index.html','/app/**/*.{js,html,css,png,jpg,gif}'],to be able to get this working?I tried replacing it with:staticFileGlobs: ['*.*'] as well. but yet I get the same message.`

**Comment by sparanoid** [comment]
Can you reproduce it with a public repo?

**Comment by sparanoid** [comment]
Feel free to reopen this issue if you have any update.
