### ISSUE TITLE
Multiple base directories

### ISSUE THREAD

**Issue by brunowego** [sparanoid/grunt-service-worker#3]
I'm getting around this, but it would be great to have that support.

```js
module.exports = {
  options: {
    workerFile: 'sw.js'
  },
  build: {
    options: {
      baseDir: './dist'
    }
  },
  dev: {
    options: {
      baseDir: ['./public', './tmp'], // multiple directories :)
      workerDir: './tmp'
    }
  }
};
```

Does it make sense to support more than one directory?

**Comment by sparanoid** [comment]
What use case of getting more than one source dir?

I'm also too busy these days to get to this, it'd be great if you can make a PR for this.

**Comment by brunowego** [comment]
@sparanoid thanks for the reply. I am not working on this more. Sorry about that, but I forgot the reason for this. I will close this.
